/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    media: Media;
    users: User;
  };
  globals: {
    header: Header;
    footer: Footer;
    home: Home;
    publications: Publication;
  };
}
export interface Media {
  id: string;
  alt: string;
  src: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Header {
  id: string;
  logo: string | Media;
  navigations: {
    href: string;
    text: string;
    id?: string;
  }[];
}
export interface Footer {
  id: string;
  columns: {
    content: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
}
export interface Home {
  id: string;
  title: string;
  description: string;
  favicon: string | Media;
  primaryHeader: string;
  secondaryHeader: string;
  content: {
    [k: string]: unknown;
  }[];
  buttonText: string;
  downloadFile: string;
  profilePicture: string | Media;
}
export interface Publication {
  id: string;
  title: string;
  publications: {
    content: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
}
